var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(app)/profile/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__a7fa4ebe._.js")
R.c("server/chunks/ssr/_0efddc1b._.js")
R.c("server/chunks/ssr/_fa26246c._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1257d2b0._.js")
R.c("server/chunks/ssr/[root-of-the-server]__a64655ed._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__12527cb5._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/src_app_(app)_layout_tsx_9b49dfb0._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(app)_profile_page_actions_8128b412.js")
R.m(22934)
module.exports=R.m(22934).exports
